# Generated by Django 2.2.5 on 2020-09-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200907_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verified',
            new_name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_secret',
        ),
    ]
